services:
  database:
    container_name: marcocarmonadev-backend-database
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/

volumes:
  postgres-data:
    name: "marcocarmonadev-backend-postgres-data"
