include:
  - docker-compose.base.yml

services:
  backend:
    image: marcocarmonadev-backend
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marcocarmonadev-backend
    depends_on:
      - database
    env_file:
      - .envs/production.env
    ports:
      - "8000:8000"

networks:
  default:
    name: marcocarmonadev-backend-default
