services:
  database:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: marcocarmonadev-backend-database
    networks:
      - PostgreSQL
      - default
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
    name: "marcocarmonadev-backend-postgres-data"

networks:
  PostgreSQL:
    external: true
