include:
  - ../docker-compose.base.yml

services:
  devcontainer:
    command: sleep infinity
    container_name: marcocarmonadev-backend-devcontainer
    depends_on:
      - database
    env_file:
      - ../.envs/develoment.env
    image: mcr.microsoft.com/devcontainers/python:3.12
    volumes:
      - ../:/workspace/:cached
